# Generated by Django 3.0.14 on 2021-12-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_create_brand_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlevel',
            name='total_point',
        ),
        migrations.AddField(
            model_name='user',
            name='total_point',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Total Point'),
        ),
        migrations.AddField(
            model_name='userlevel',
            name='current_level_minimum_point',
            field=models.PositiveIntegerField(default=10, verbose_name='Current Level Minimum Point'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userlevel',
            name='next_level_minimum_point',
            field=models.PositiveIntegerField(default=10, verbose_name='Next Level Minimum Point'),
            preserve_default=False,
        ),
    ]
