# Generated by Django 3.0.14 on 2022-01-05 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_update_usermanager_and_create_blank_true_user_level_filed_in_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='total_point',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Total Point'),
        ),
    ]
