# Generated by Django 3.0.14 on 2022-01-06 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_user_level_using_enum_field_change_integer_field_to_char_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_level', to='member.UserLevel', verbose_name='User Level'),
        ),
        migrations.AlterField(
            model_name='userlevel',
            name='discount_rate',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Discount Rate'),
        ),
        migrations.AlterField(
            model_name='userlevel',
            name='monthly_discount_coupon_count',
            field=models.PositiveIntegerField(default=3, verbose_name='Monthly Discount Coupon Count'),
        ),
        migrations.AlterField(
            model_name='userlevel',
            name='monthly_discount_coupon_rate',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Monthly Discount Coupon Rate'),
        ),
    ]
