# Generated by Django 3.0.14 on 2022-01-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_change_onetoone_to_foreignkey_user_level_field_in_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlevel',
            name='level_name',
            field=models.CharField(choices=[('1', 'Noob'), ('2', 'Rookie'), ('3', 'Member'), ('4', 'Bronze'), ('5', 'Silver'), ('6', 'Gold'), ('7', 'Platinum'), ('8', 'Diamond')], default='1', max_length=10, verbose_name='Level Name'),
        ),
    ]
