# Generated by Django 3.0.14 on 2021-12-27 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_switch_foreignkey_brand_to_clothes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('parent_category', models.IntegerField(default=1, verbose_name='Parent Category')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='shop.Category', verbose_name='Categories')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Category List',
                'db_table': 'category',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=10, verbose_name='Name')),
                ('image_url', models.ImageField(upload_to='color/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Color List',
                'db_table': 'color',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('fit', models.CharField(blank=True, max_length=10, verbose_name='Fit')),
                ('touch', models.CharField(blank=True, max_length=10, verbose_name='Touch')),
                ('flexibility', models.CharField(blank=True, max_length=10, verbose_name='Flexibility')),
                ('see_through', models.CharField(blank=True, max_length=10, verbose_name='See Through')),
                ('thickness', models.CharField(blank=True, max_length=10, verbose_name='Thickness')),
                ('Season', models.CharField(blank=True, max_length=10, verbose_name='Season')),
            ],
            options={
                'verbose_name': 'Clothes Guide',
                'verbose_name_plural': 'Clothes Guide List',
                'db_table': 'clothes_guide',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('size', models.IntegerField(blank=True, default=0, verbose_name='Size')),
                ('size_code', models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('2XL', '2XL'), ('F', 'Free')], max_length=3, verbose_name='Size Code')),
                ('outseam', models.IntegerField(default=0, verbose_name='Outseam')),
                ('shoulder_width', models.IntegerField(default=0, verbose_name='Shoulder Width')),
                ('chest_width', models.IntegerField(default=0, verbose_name='Chest Width')),
                ('sleeve_length', models.IntegerField(default=0, verbose_name='Sleeve Length')),
                ('waist_width', models.IntegerField(default=0, verbose_name='Waist Width')),
                ('thigh_width', models.IntegerField(default=0, verbose_name='Thigh Width')),
                ('rise', models.IntegerField(default=0, verbose_name='Rise')),
                ('hem', models.IntegerField(default=0, verbose_name='Hem')),
                ('clothes_division', models.CharField(choices=[('O', 'Outer'), ('T', 'Top'), ('P', 'Pants'), ('S', 'Shoes')], max_length=1, verbose_name='Clothes Division')),
            ],
            options={
                'verbose_name': 'Size',
                'verbose_name_plural': 'Size List',
                'db_table': 'size',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='clothes',
            name='image_url',
            field=models.ImageField(default='', upload_to='clothes/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ClothesColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('clothes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clothes_in_clothes_color', to='shop.Clothes', verbose_name='Clothes')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='color_in_clothes_color', to='shop.Color', verbose_name='Color')),
            ],
            options={
                'verbose_name': 'Clothes Color',
                'verbose_name_plural': 'Clothes Color List',
                'db_table': 'clothes_color',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ClothesCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_in_clothes_category', to='shop.Category', verbose_name='Category')),
                ('clothes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clothes_in_clothes_category', to='shop.Clothes', verbose_name='Clothes')),
            ],
            options={
                'verbose_name': 'Clothes Category',
                'verbose_name_plural': 'Clothes Category List',
                'db_table': 'clothes_category',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='clothes',
            name='categories',
            field=models.ManyToManyField(blank=True, through='shop.ClothesCategory', to='shop.Category', verbose_name='Categories'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='color',
            field=models.ManyToManyField(blank=True, through='shop.ClothesColor', to='shop.Color', verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='guide',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clothes_guide', to='shop.Guide', verbose_name='Guide'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='size',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clothes_size', to='shop.Size', verbose_name='Size'),
        ),
    ]
