# Generated by Django 3.0.14 on 2022-01-04 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_modify_category_size_clothes_field_conditions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guide',
            old_name='Season',
            new_name='season',
        ),
    ]
