# Generated by Django 3.0.14 on 2022-01-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_update_usermanager_and_create_blank_true_user_level_filed_in_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='size',
        ),
        migrations.AddField(
            model_name='clothes',
            name='size',
            field=models.ManyToManyField(blank=True, related_name='clothes_size', to='shop.Size', verbose_name='Size'),
        ),
    ]
