# Generated by Django 3.0.14 on 2022-01-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_size_field_change_onetoone_to_manytomany_in_clothes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='unique_number',
            field=models.CharField(max_length=50, verbose_name='Unique Number'),
        ),
    ]
