# Generated by Django 3.0.14 on 2022-01-18 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_update_usermanager_and_create_blank_true_user_level_filed_in_user'),
        ('orders', '0001_create_initial_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='clothes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes_in_order_items', to='shop.Clothes', verbose_name='Clothes'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='discount_coupon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_coupon_in_order_items', to='orders.DiscountCoupon', verbose_name='Discount Coupon'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_in_order_items', to='orders.Order', verbose_name='Order'),
            preserve_default=False,
        ),
    ]
