# Generated by Django 3.0.14 on 2022-01-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_blank_and_null_option_from_order_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcoupon',
            name='type',
            field=models.CharField(choices=[('Period', 'Period'), ('Brand', 'Brand')], default='Period', max_length=10, verbose_name='Type'),
        ),
    ]
