# Generated by Django 3.0.14 on 2022-01-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_create_type_field_in_discount_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcoupon',
            name='disabled_at',
            field=models.DateTimeField(verbose_name='Disabled At'),
        ),
    ]
