# Generated by Django 3.0.14 on 2022-01-20 12:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_disabled_at_field_change_auto_now_is_false'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountcoupon',
            name='user',
        ),
        migrations.AddField(
            model_name='discountcoupon',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
