# Generated by Django 3.0.14 on 2022-01-26 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0005_chagne_user_field_foreignkey_to_manytomany_in_discountcoupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='consumer',
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_in_order', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='discountcoupon',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='user_in_discount_coupon', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
