# Generated by Django 3.0.14 on 2022-02-08 16:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_user_field_change_foreignkey_in_order_and_user_field_change_manytomany_in_discount_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Delivery Address'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_memo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Delivery Memo'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='recipient_name'),
        ),
        migrations.AddField(
            model_name='order',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UID'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='amount',
            field=models.PositiveIntegerField(default=1, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.Order', verbose_name='Order'),
        ),
    ]
