# Generated by Django 3.0.14 on 2022-02-10 10:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20220208_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcoupon',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UID'),
        ),
    ]
